# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smartfox}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Penwell"]
  s.date = %q{2010-06-08}
  s.description = %q{Provides a client library for the SmartFox realtime communication server, including BlueBox extensions.}
  s.email = %q{self@richardpenwell.me}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/smartfox.rb",
     "lib/smartfox/blue_box.rb",
     "lib/smartfox/blue_box/connection.rb",
     "lib/smartfox/client.rb",
     "lib/smartfox/message.rb",
     "lib/smartfox/packet.rb",
     "lib/smartfox/room.rb",
     "lib/smartfox/socket.rb",
     "lib/smartfox/socket/connection.rb",
     "lib/smartfox/user.rb",
     "smartfox.gemspec",
     "spec/packet_spec.rb",
     "spec/smartfox_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/waiter.rb"
  ]
  s.homepage = %q{http://github.com/penwellr/smartfox}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Client library for SmartFoxServer}
  s.test_files = [
    "spec/packet_spec.rb",
     "spec/smartfox_spec.rb",
     "spec/spec_helper.rb",
     "spec/waiter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
  end
end

